name: Trigger Repo flow on Commit

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  notify-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in Repo
        env:
          RT_GH_PAT: ${{ secrets.RT_GH_PAT }}
        run: |
          echo "Token starts with: ${RT_GH_PAT:0:4}"  # optional debug
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $RT_GH_PAT" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/M-ichae-l/My-private-test/actions/workflows/download-and-commit-pdf.yml/dispatches \
            -d '{"ref":"main"}'

